/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedProjectIndexRouteImport } from './routes/_authenticated/project/index'
import { Route as AuthenticatedHomeIndexRouteImport } from './routes/_authenticated/home/index'
import { Route as AuthenticatedExperienceIndexRouteImport } from './routes/_authenticated/experience/index'
import { Route as AuthenticatedAboutIndexRouteImport } from './routes/_authenticated/about/index'
import { Route as AuthenticatedProjectRegisterIndexRouteImport } from './routes/_authenticated/project/register/index'
import { Route as AuthenticatedProjectSlugIndexRouteImport } from './routes/_authenticated/project/$slug/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectIndexRoute =
  AuthenticatedProjectIndexRouteImport.update({
    id: '/project/',
    path: '/project/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHomeIndexRoute = AuthenticatedHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExperienceIndexRoute =
  AuthenticatedExperienceIndexRouteImport.update({
    id: '/experience/',
    path: '/experience/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAboutIndexRoute = AuthenticatedAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectRegisterIndexRoute =
  AuthenticatedProjectRegisterIndexRouteImport.update({
    id: '/project/register/',
    path: '/project/register/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectSlugIndexRoute =
  AuthenticatedProjectSlugIndexRouteImport.update({
    id: '/project/$slug/',
    path: '/project/$slug/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/about': typeof AuthenticatedAboutIndexRoute
  '/experience': typeof AuthenticatedExperienceIndexRoute
  '/home': typeof AuthenticatedHomeIndexRoute
  '/project': typeof AuthenticatedProjectIndexRoute
  '/project/$slug': typeof AuthenticatedProjectSlugIndexRoute
  '/project/register': typeof AuthenticatedProjectRegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/about': typeof AuthenticatedAboutIndexRoute
  '/experience': typeof AuthenticatedExperienceIndexRoute
  '/home': typeof AuthenticatedHomeIndexRoute
  '/project': typeof AuthenticatedProjectIndexRoute
  '/project/$slug': typeof AuthenticatedProjectSlugIndexRoute
  '/project/register': typeof AuthenticatedProjectRegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_authenticated/about/': typeof AuthenticatedAboutIndexRoute
  '/_authenticated/experience/': typeof AuthenticatedExperienceIndexRoute
  '/_authenticated/home/': typeof AuthenticatedHomeIndexRoute
  '/_authenticated/project/': typeof AuthenticatedProjectIndexRoute
  '/_authenticated/project/$slug/': typeof AuthenticatedProjectSlugIndexRoute
  '/_authenticated/project/register/': typeof AuthenticatedProjectRegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/about'
    | '/experience'
    | '/home'
    | '/project'
    | '/project/$slug'
    | '/project/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/about'
    | '/experience'
    | '/home'
    | '/project'
    | '/project/$slug'
    | '/project/register'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth/login'
    | '/_authenticated/about/'
    | '/_authenticated/experience/'
    | '/_authenticated/home/'
    | '/_authenticated/project/'
    | '/_authenticated/project/$slug/'
    | '/_authenticated/project/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/project/': {
      id: '/_authenticated/project/'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof AuthenticatedProjectIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home/': {
      id: '/_authenticated/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/experience/': {
      id: '/_authenticated/experience/'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof AuthenticatedExperienceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/about/': {
      id: '/_authenticated/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/register/': {
      id: '/_authenticated/project/register/'
      path: '/project/register'
      fullPath: '/project/register'
      preLoaderRoute: typeof AuthenticatedProjectRegisterIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/$slug/': {
      id: '/_authenticated/project/$slug/'
      path: '/project/$slug'
      fullPath: '/project/$slug'
      preLoaderRoute: typeof AuthenticatedProjectSlugIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAboutIndexRoute: typeof AuthenticatedAboutIndexRoute
  AuthenticatedExperienceIndexRoute: typeof AuthenticatedExperienceIndexRoute
  AuthenticatedHomeIndexRoute: typeof AuthenticatedHomeIndexRoute
  AuthenticatedProjectIndexRoute: typeof AuthenticatedProjectIndexRoute
  AuthenticatedProjectSlugIndexRoute: typeof AuthenticatedProjectSlugIndexRoute
  AuthenticatedProjectRegisterIndexRoute: typeof AuthenticatedProjectRegisterIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAboutIndexRoute: AuthenticatedAboutIndexRoute,
  AuthenticatedExperienceIndexRoute: AuthenticatedExperienceIndexRoute,
  AuthenticatedHomeIndexRoute: AuthenticatedHomeIndexRoute,
  AuthenticatedProjectIndexRoute: AuthenticatedProjectIndexRoute,
  AuthenticatedProjectSlugIndexRoute: AuthenticatedProjectSlugIndexRoute,
  AuthenticatedProjectRegisterIndexRoute:
    AuthenticatedProjectRegisterIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
